### ISSUE TITLE
Better parsing the RPC and gRPC endpoints

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#353]
Currently, when specifying an RPC or gRPC endpoint, if we add an extra `/` at the end, or we miss the format, the orchestrator/relayer returns an error. We should make these possibilities also work to make it easier for validators to run the binary.

**Comment by WayneWayner** [comment]
I want to add that validators might want to use domains to connect to their RPC endpoints. When trying so you will end up with following example:
```
Error: dial tcp: address celestia.rpc.waynewayner.de: missing port in address
```

**Comment by SweeXordious** [comment]
Good point, thanks. Should also be fixed
