### ISSUE TITLE
Rename QGB to Blobstream in About

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/orchestrator-relayer#572]
## Problem

The About section of this repo still references QGB

## Screenshot

<img width="346" alt="Screenshot 2023-10-31 at 8 06 22 PM" src="https://github.com/celestiaorg/orchestrator-relayer/assets/3699047/94a6c0cb-f526-4376-9f67-0fb8d994ac8f">

## Proposal

Someone with permission to edit the About should update it to say Blobstream.

**Comment by SweeXordious** [comment]
Done

**Comment by SweeXordious** [comment]
Great catch btw :+1: :+1:
