### ISSUE TITLE
Question about relaying to already deployed contracts

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/orchestrator-relayer#599]
## Context

https://github.com/celestiaorg/orchestrator-relayer/blob/17b5716fcefab6f7afed237f4f1bc207f52d2095/README.md?plain=1#L30

## Question

What if the blobstream contracts are already deployed to a network and I as a relayer don't want to deploy the contracts again but want to relay to an existing set of deployed contracts? Is that supported?

**Comment by SweeXordious** [comment]
yes, will update the docs
