### ISSUE TITLE
Add attestation confirms marshal/unmarshal methods

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#69]
In preparation for the QGB V2 network defined under https://github.com/celestiaorg/orchestrator-relayer/pull/66, we should provide marshal and umarshal helpers for attestation confirms  types in order to be used in the DHT.

For now, we can use simple Json marshal and eventually move to something better if there is a need for it.

**Comment by evan-forbes** [comment]
what were we using before? could we use gogoproto like the rest of the things in the sdk given that this is for signatures?

**Comment by SweeXordious** [comment]
These will be the values stored inside the DHT. They're unrelated to the sdk, that's why I thought to go for something simple, without having to define proto files and generate code. 

I am fine with using gogoproto, I just don't see what it would add over simple json

**Comment by evan-forbes** [comment]
yeah, good point. I was thinking that using something deterministic would avoid weird bugs of pitfalls if the hash of that data was used for anything

**Comment by SweeXordious** [comment]
Hum, I see, based on the structs we will be marhsalling/unmarshalling, the data is small and contains hex strings, addresses etc, which are standard strings:
```
// DataCommitmentConfirm describes a data commitment for a set of blocks.
type DataCommitmentConfirm struct {
	// Signature over the commitment, the range of blocks, the validator address
	// and the Ethereum address.
	Signature string
	// Hex `0x` encoded Ethereum public key that will be used by this validator on
	// Ethereum.
	EthAddress string
	// Merkle root over a merkle tree containing the data roots of a set of
	// blocks.
	Commitment string
}
```
Also, the size is of 128bytes, I guess  or so, so it's not much data.

Yes, protobuf is more efficient when encrypting random binary data or large data, but I don't think we have that.

Let me know if I am missing something so that I change to protobuf.
