### ISSUE TITLE
Orchestrator address <> EVM address mapping

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#89]
Currently, as defined by https://github.com/celestiaorg/orchestrator-relayer/pull/66, we are indexing confirms by `<nonce>:<orchestrator_address>`. 

Also, when defining a valset on the state machine, we're keeping a list of validators EVM addresses.

The problem is, for a given confirm to be retrieved, we will need to have access to its corresponding `orchestrator_address` which we don't have access to all the time, since the valsets only keep the EVM addresses.

Suggestion: change the keys of the confirms from `<nonce>:<orchestrator_address>` to `<nonce>:<evm_address>`.

This way, we will have access to any confirm provided we have the valset that signed it, which is already stored in the state machine.

**Comment by SweeXordious** [comment]
cc @evan-forbes @rahulghangas

**Comment by evan-forbes** [comment]
makes sense to me. we might need to also think about how the relayer/orchestrator listens for evm address changes

**Comment by SweeXordious** [comment]
IF a validator changes its EVM address, it will need to restart its orchestrator with the private key corresponding to it. 

For the relayer, the EVM changes will be reflected by valsets, and it will look for confirms according to the new EVM address. 

Also, this change I guess is inevitable if we decide to delete the orchestrator address.
